services:
  postgis:
    image: postgis/postgis
    container_name: checkdam_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      # POSTGRES_DB: checkdam
    ports:
      - "5436:5432"
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d

  nodejs:
    image: node:latest
    container_name: checkdam_nodejs
    working_dir: /app
    depends_on:
      - postgis
    volumes:
      - ./nodejs:/app
    ports:
      - "3300:3000"
    command:
      - bash
      - -c
      - npm i  && npm i -g nodemon && nodemon
